# Base Alpine Linux based image with OpenJDK JRE only
FROM openjdk:8-jre-alpine

COPY /Users/vish/IdeaProjects/test-ci/pom.xml pipeline/

COPY /Users/vish/IdeaProjects/test-ci/src pipeline/src

WORKDIR pipeline/

RUN mvn clean install

# copy application JAR (with libraries inside)
COPY target/*.jar /app.jar
# specify default command
CMD ["java", "-jar", "/app.jar"]
